version: '4.29.0'

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html

  mysql:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: inventorymgtci
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
